### PR TITLE
build: bump to use go1.17

### PR DESCRIPTION
**Pull request by chenrui333**
### Changes Introduced
- update build to use [latest go1.17](https://go.dev/blog/go1.17)

---

relates to Homebrew/homebrew-core#83413

### CODE REVIEW

**Comment by chenrui333** [comment]
cc @InTheCloudDan @yusinto

**Comment by vlymar** [comment]
Thanks for opening this PR! We'll look into merging this PR soon :)

**Comment by chenrui333** [comment]
Thanks @vlymar!! :)

**Comment by carmenquan** [comment]
Thanks @chenrui333!

**Pull request merged**
